/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.flight.booking.main;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication(exclude = HibernateJpaAutoConfiguration.class)
@ComponentScan("com.flight.booking")
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	public boolean someLibraryMethod() {
		return true;
	}
}
